name: Python package

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: ['chrome', 'firefox', 'edge'] 
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Set up Chrome
        if: matrix.browser == 'chrome'
        uses: browser-actions/setup-chrome@v1

      - name: Set up Firefox
        if: matrix.browser == 'firefox'
        uses: browser-actions/setup-firefox@v1
      
      - name: Set up Edge
        if: matrix.browser == 'edge'
        uses: browser-actions/setup-edge@v1
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Run tox
        run: tox
        env:
          BROWSER: ${{ matrix.browser }}

  publish:
    needs: test
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Build
        run: python setup.py sdist

      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
            user: invoker
            password: ${{ secrets.PYPI_API_TOKEN }}
            repository-url: https://test.pypi.org/
            packages-dir: dist/
            skip-existing: true
            verbose: true
